[bot]
token = "YourVeryComplicated:BotToken"
debug = false

[channels]
channel_1 = "-123456789"
# channel_2 = "your_second_channel"
# channel_3 = "your_third_channel"

[poll]
question = "Päivän Sanapyramidin suoritukset"
options = ["0 virhettä", "1 virhe", "2 virhettä", "3 virhettä", "Vituix män"]

[schedule]
hour = 7
minute = 15
